name: Reusable security-events test
on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  hello:
    runs-on: [self-hosted, Linux]
    steps:
      - run: echo "reusable met security-events werkt"
