name: Semgrep tmp test
on:
  push:
    branches: [semgrep-test]
  workflow_dispatch:
jobs:
  semgrep:
    uses: m0nklabs/github-action-runners/.github/workflows/semgrep-ci.yml@main
    with:
      config: auto
      fail-on: none
    secrets: inherit
